# Generated by Django 5.0 on 2023-12-12 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Buyer_Volate',
            new_name='Buyer_wallet',
        ),
    ]
